version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/php:8.3.4

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  
commands:

  mi-hola:
    parameters:
      message:
        type: string
        default: "Hola mundo"
    steps:
      - run: echo << parameters.message >>

  generar-saludo:
    parameters:
      nombre:
        type: string
        default: "Juan"
    steps:
      - run: php lib/greet.php << parameters.nombre >> > greetings.txt
      - run: |
          ls -l
          if [ -f greetings.txt ]; then
            echo "El archivo greetings.txt se ha creado correctamente."
            cat greetings.txt  # Esto imprimirá el contenido del archivo
          else
            echo "¡El archivo greetings.txt no se ha creado!"
            exit 1
          fi

jobs:

  hello-job:
    <<: *defaults
    steps:
      - checkout
      - mi-hola
      - sonarcloud/scan

  greet-job:
    <<: *defaults
    steps:
      - checkout
      - generar-saludo:
          nombre: "Pedro"
      

workflows:
  mi-php-workflow-01:
    jobs:
      - hello-job:
          context: SonarCloud
      - greet-job
