version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/php:8.3.4

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  
commands:

  mi-hola:
    parameters:
      message:
        type: string
        default: "Hola mundo"
    steps:
      - run: echo << parameters.message >>

jobs:

  hello-job:
    <<: *defaults
    steps:
      - checkout
      - mi-hola
      - sonarcloud/scan
      

workflows:
  mi-php-workflow-01:
    jobs:
      - hello-job:
          context: SonarCloud
